### PR TITLE
Feature: Add radar chart to the homepage

### PR DESCRIPTION
**Pull request by jar0s**
First of all, thank you for open-sourcing your Tech Radar app. It's great!
Second, this is my first open-source contribution ever so please be gentle :wink:

The code is inspired by [this blog post](https://medium.com/create-code/build-a-radar-diagram-with-d3-js-9db6458a9248) and combines info from [that one](https://pganalyze.com/blog/building-svg-components-in-react) as well.

The end result is:
aoe_techradar

The chart is configurable (sizes, colors, etc.) and I added a config option to control what you'd like to see on the homepage (radar chart, current quadrant grid, or both) as well.

Known issues:
* Currently the `RadarGrid` component is not responsive and won't look good on smaller screens or mobile. It would be great if someone could help me with that as I'm not really a frontend dev :wink: 

Ideas for future improvements:
* Add option to see chart in quadrant overview, just like on [this tech radar](https://data-radar.mediaman.com/)
* Change the algorithm of positioning the blips on the chart to more deterministic (currently it's based on `Math.random()`) to keep the location of items more-less the same between page refreshes.

### CODE REVIEW

**Comment by lacy-llana** [comment]
@jar0s This is super slick! I'm not with AOE so can't do anything to merge it in, but have had an issue open with this repo for awhile and it seems like you may have an idea of how to accomplish what I'm trying to do. In bringing the repo down locally and making changes, I can't get it to successfully build by referencing my internal repo.

`yarn add https://gitlab.com/my-internal-repo.git` results in: 

`error An unexpected error occurred: "https://registry.yarnpkg.com/aoe_technology_radar: Not found"`

If you have any tips on how to successfully reference the builder code from the external radar repo, it would be greatly appreciated!

**Comment by jar0s** [comment]
Hi @lacy-llana 
I'm glad you like it :)
I didn't get to using my forked repo to actually build an external radar. I was only running the "builder" project directly locally.

Looking at the [npm docs](https://docs.npmjs.com/cli/v7/commands/npm-install) it seems like there's a different syntax for adding a dependency straight from a GitLab repo.  Try `npm install gitlab:mygitlabuser/myproject`. Yarn doesn't mention the option of adding a dependency from GitLab in [its docs](https://classic.yarnpkg.com/en/docs/cli/add/). Also, I believe the repository needs to be public to be able to reference it like that.

**Comment by danielpoe** [comment]
Thanks @jar0s and @4integration for the contribution and report - we are currently updating our radar version as well and will have a look soon.

**Comment by jar0s** [comment]
Cheers @danielpoe 
Please let me know when you're done with your changes and I will have a look at the conflicts then.

**Comment by Karreg** [comment]
Hello,

I'm coming from #99. I second this request and MR. The result looks great :)

**Comment by bastianccm** [comment]
Yes, I'm on it, hope to find some time next week!

**Comment by jar0s** [comment]
Thank you @bastianccm . It was super busy time for me the last few months so I appreciate your help to get this back in shape.

**Comment by bastianccm** [comment]
Merged :)

Some Leftovers we need to tackle before creating a new release:
https://github.com/AOEpeople/aoe_technology_radar/issues/112
https://github.com/AOEpeople/aoe_technology_radar/issues/113

**Comment by MicTech** [comment]
> Merged :)
> 
> 
> 
> Some Leftovers we need to tackle before creating a new release:
> 
> https://github.com/AOEpeople/aoe_technology_radar/issues/112
> 
> https://github.com/AOEpeople/aoe_technology_radar/issues/113
> 
> 

Thank you 🙏

**Pull request merged**
